CREATE TABLE PROYECTO (
    IdProyecto INT IDENTITY(1,1) PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE PRODUCTO (
    IdProducto INT IDENTITY(1,1) PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE TIPO (
    IdTipo INT IDENTITY(1,1) PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE TIPO_INFORMACION (
    IdTipoInfo INT IDENTITY(1,1) PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE PROYECTO_PRODUCTO (
    IdProyecto INT NOT NULL,
    IdProducto INT NOT NULL,
    CONSTRAINT PK_PROYECTO_PRODUCTO PRIMARY KEY (IdProyecto, IdProducto),
    CONSTRAINT FK_PP_PROYECTO FOREIGN KEY (IdProyecto)
        REFERENCES PROYECTO(IdProyecto)
        ON DELETE CASCADE,
    CONSTRAINT FK_PP_PRODUCTO FOREIGN KEY (IdProducto)
        REFERENCES PRODUCTO(IdProducto)
        ON DELETE CASCADE
);

CREATE TABLE FORMATO_MENSAJE (
    IdFormato INT IDENTITY(1,1) PRIMARY KEY,
    IdTipo INT NOT NULL,
    IdTipoInfo INT NOT NULL,
    Nombre VARCHAR(150) NOT NULL,
    Remitente VARCHAR(150),
    Asunto VARCHAR(200),
    CONSTRAINT FK_FM_TIPO FOREIGN KEY (IdTipo)
        REFERENCES TIPO(IdTipo),
    CONSTRAINT FK_FM_TIPOINFO FOREIGN KEY (IdTipoInfo)
        REFERENCES TIPO_INFORMACION(IdTipoInfo)
);

CREATE TABLE MENSAJE (
    IdMensaje INT IDENTITY(1,1) PRIMARY KEY,
    IdFormato INT NOT NULL,
    IdProyecto INT NOT NULL,
    IdProducto INT NOT NULL,
    FechaCreacion DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_MENSAJE_FORMATO FOREIGN KEY (IdFormato)
        REFERENCES FORMATO_MENSAJE(IdFormato),
    CONSTRAINT FK_MENSAJE_PROYECTO FOREIGN KEY (IdProyecto)
        REFERENCES PROYECTO(IdProyecto),
    CONSTRAINT FK_MENSAJE_PRODUCTO FOREIGN KEY (IdProducto)
        REFERENCES PRODUCTO(IdProducto)
);
